//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace florist.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class bouquetStructure
    {
        public int structureID { get; set; }
        public int bouquetID { get; set; }
        public int flowerID { get; set; }
    
        public virtual bouquet bouquet { get; set; }
        public virtual flowers flowers { get; set; }
    }
}
