//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace florist.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FloristEntities : DbContext
    {
        public FloristEntities()
            : base("name=FloristEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<allProducts> allProducts { get; set; }
        public virtual DbSet<basket> basket { get; set; }
        public virtual DbSet<blossomSize> blossomSize { get; set; }
        public virtual DbSet<bouquet> bouquet { get; set; }
        public virtual DbSet<bouquetStructure> bouquetStructure { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<color> color { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<flowers> flowers { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<salePoint> salePoint { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
